# Generated by Django 5.2.7 on 2025-11-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="任务编号"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="任务/患者名称"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="病情备注"),
                ),
                (
                    "patient_file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="加密病例路径",
                    ),
                ),
                (
                    "source_video_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="原始视频路径",
                    ),
                ),
                ("video_fps", models.IntegerField(default=30, verbose_name="抽帧频率")),
                (
                    "sample_count",
                    models.IntegerField(default=0, verbose_name="样本数量"),
                ),
                (
                    "labeled_count",
                    models.IntegerField(default=0, verbose_name="已标注数"),
                ),
                ("state", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建医生",
                    ),
                ),
            ],
            options={
                "verbose_name": "病例任务",
                "verbose_name_plural": "病例任务",
                "db_table": "core_label_task",
            },
        ),
        migrations.CreateModel(
            name="SampleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="样本编号")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="图片路径"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=200, verbose_name="文件名"),
                ),
                (
                    "is_labeled",
                    models.BooleanField(default=False, verbose_name="是否已标注"),
                ),
                (
                    "annotation_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="标注数据(XML/JSON)"
                    ),
                ),
                (
                    "labeled_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="标注员"
                    ),
                ),
                (
                    "labeled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="标注时间"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="core.labeltask",
                    ),
                ),
            ],
            options={
                "verbose_name": "样本图片",
                "db_table": "core_sample_image",
            },
        ),
    ]
