# Generated by Django 5.2.7 on 2025-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_taskfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampleimage",
            name="audit_reason",
            field=models.TextField(blank=True, null=True, verbose_name="驳回修改意见"),
        ),
        migrations.AddField(
            model_name="sampleimage",
            name="audit_status",
            field=models.IntegerField(
                choices=[(0, "待审核"), (1, "已通过"), (2, "已驳回")],
                default=0,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="labeltask",
            name="name",
            field=models.CharField(max_length=100, verbose_name="任务/患者名称"),
        ),
    ]
