# Generated by Django 5.2.7 on 2025-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="所属科室"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
    ]
