# Generated by Django 5.2.7 on 2025-12-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_operationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/user.png",
                null=True,
                upload_to="avatars/%Y/%m/",
                verbose_name="用户头像",
            ),
        ),
    ]
